import {
  Globe,
  MapPin,
  Flag,
  Building2,
  Building,
  Landmark,
  Castle,
  Church,
  Tent,
  Mic2,
  Music,
  Music2,
  Flame,
  PartyPopper,
  Sparkles,
  Crown,
  Trophy,
  Medal,
  Star,
  Heart,
  Users,
  User,
  UserCircle,
  Baby,
  Skull,
  Cross,
  Swords,
  Shield,
  Target,
  Bomb,
  Radiation,
  AlertTriangle,
  Ship,
  Plane,
  Car,
  Train,
  Bike,
  Rocket,
  Moon,
  Sun,
  Cloud,
  Snowflake,
  Waves,
  Mountain,
  TreePine,
  Leaf,
  Bug,
  Bird,
  Fish,
  Cat,
  Dog,
  Gamepad2,
  Joystick,
  Monitor,
  Smartphone,
  Tablet,
  Tv,
  Radio,
  Headphones,
  Camera,
  Video,
  Film,
  Clapperboard,
  Popcorn,
  Gift,
  Package,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Coins,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Lightbulb,
  Cpu,
  Bot,
  MessageCircle,
  Mail,
  Send,
  Search,
  Eye,
  BookOpen,
  GraduationCap,
  School,
  Library,
  Dumbbell,
  Timer,
  Clock,
  Calendar,
  Newspaper,
  Scroll,
  FileText,
  Hash,
  AtSign,
  Globe2,
  Network,
  Wifi,
  Signal,
  CircleDot,
  Footprints,
  Handshake,
  Brain,
  Dna,
  Atom,
  FlaskConical,
  Microscope,
  Stethoscope,
  Pill,
  Syringe,
  Thermometer,
  Coffee,
  Wine,
  Utensils,
  Pizza,
  Apple,
  Carrot,
  Wheat,
  Tractor,
  Factory,
  HardHat,
  Hammer,
  Wrench,
  Palette,
  Brush,
  Pen,
  Pencil,
  Scissors,
  Ruler,
  Compass,
  Map,
  Navigation,
  LocateFixed,
  Home,
  Hotel,
  BedDouble,
  Sofa,
  Armchair,
  Lamp,
  Fan,
  Droplet,
  Wind,
  Umbrella,
  CloudRain,
  Sunrise,
  Sunset,
  Eclipse,
  X,
} from "lucide-react";

// Map icon names to components
const iconMap = {
  // Globe & World
  globe: Globe,
  globe2: Globe2,
  "map-pin": MapPin,
  flag: Flag,
  map: Map,
  navigation: Navigation,
  "locate-fixed": LocateFixed,

  // Buildings & Places
  building2: Building2,
  building: Building,
  landmark: Landmark,
  castle: Castle,
  church: Church,
  home: Home,
  hotel: Hotel,
  school: School,
  library: Library,
  factory: Factory,
  tent: Tent,

  // Music & Entertainment
  mic2: Mic2,
  music: Music,
  music2: Music2,
  headphones: Headphones,
  radio: Radio,
  film: Film,
  clapperboard: Clapperboard,
  popcorn: Popcorn,
  tv: Tv,
  video: Video,
  camera: Camera,

  // Events
  flame: Flame,
  "party-popper": PartyPopper,
  sparkles: Sparkles,
  crown: Crown,

  // Sports & Competition
  trophy: Trophy,
  medal: Medal,
  star: Star,
  dumbbell: Dumbbell,
  timer: Timer,
  bike: Bike,

  // People
  users: Users,
  user: User,
  "user-circle": UserCircle,
  baby: Baby,
  brain: Brain,
  footprints: Footprints,
  handshake: Handshake,

  // Death & Disaster
  skull: Skull,
  cross: Cross,
  swords: Swords,
  shield: Shield,
  target: Target,
  bomb: Bomb,
  radiation: Radiation,
  "alert-triangle": AlertTriangle,
  waves: Waves,

  // Transport
  ship: Ship,
  plane: Plane,
  car: Car,
  train: Train,
  rocket: Rocket,

  // Space & Nature
  moon: Moon,
  sun: Sun,
  cloud: Cloud,
  snowflake: Snowflake,
  mountain: Mountain,
  "tree-pine": TreePine,
  leaf: Leaf,
  wheat: Wheat,

  // Animals
  bug: Bug,
  bird: Bird,
  fish: Fish,
  cat: Cat,
  dog: Dog,

  // Tech & Gaming
  gamepad2: Gamepad2,
  joystick: Joystick,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  cpu: Cpu,
  bot: Bot,
  network: Network,
  wifi: Wifi,
  signal: Signal,

  // Social & Communication
  "message-circle": MessageCircle,
  mail: Mail,
  send: Send,
  search: Search,
  eye: Eye,
  hash: Hash,
  "at-sign": AtSign,

  // Business & Money
  gift: Gift,
  package: Package,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  coins: Coins,
  "trending-up": TrendingUp,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,

  // Education & Learning
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  scroll: Scroll,
  "file-text": FileText,
  newspaper: Newspaper,

  // Science
  dna: Dna,
  atom: Atom,
  "flask-conical": FlaskConical,
  microscope: Microscope,

  // Health
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  thermometer: Thermometer,
  activity: Activity,
  heart: Heart,

  // Food & Drink
  coffee: Coffee,
  wine: Wine,
  utensils: Utensils,
  pizza: Pizza,
  apple: Apple,

  // Work & Tools
  "hard-hat": HardHat,
  hammer: Hammer,
  wrench: Wrench,

  // Art
  palette: Palette,
  brush: Brush,
  pen: Pen,

  // Misc
  zap: Zap,
  lightbulb: Lightbulb,
  clock: Clock,
  calendar: Calendar,
  "circle-dot": CircleDot,
  droplet: Droplet,
  wind: Wind,
  sunrise: Sunrise,
  sunset: Sunset,
  tractor: Tractor,
  x: X,
};

const PresetIcon = ({ name, size = 20, className = "" }) => {
  const IconComponent = iconMap[name] || CircleDot;
  return <IconComponent size={size} className={className} />;
};

export default PresetIcon;
